using DemoProject.Client.Service;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using Radzen;
using System.Threading.Tasks;

namespace DemoProject.Client.Pages
{
    public partial class Home
    {
        
        string htmlValue = string.Empty;
        [Parameter]
        public string? url { get; set; }
        public string? password { get; set; }
        public string passwordToOpen { get; set; }
        private string NotePassword { get; set; }
        private bool IsEditorDisabled { get; set; }

        [Inject] NavigationManager Nav { get; set; } = null!;
        [Inject] NoteService NoteService { get; set; } = null!;
        [Inject] IJSRuntime JSRuntime { get; set; } = default!;
        [Inject] NotificationServiceWrapper NotificationServiceWrapper { get; set; } = default!;    

        private bool IsOpen
        {
            get;
            set;
        } = false;
        private bool IsOpenPassword
        {
            get;
            set;
        } = false;
        private bool IsOpenPutPassword
        {
            get;
            set;
        }


        private bool showPanel = false;
        private bool IsLoading = false;
        private string noteSummary = "This is a summarized note generated by your AI component...";


        private async Task OnModalSave(string newUrl)
        {
            var newurl = await NoteService.ChangeUrlAsync(url, newUrl);
            if (newurl == true)
            {
                Nav.NavigateTo($"/{newUrl}", true);
            }
            else
            {
                NotificationServiceWrapper.ShowError("Error changing URL!");
            }


        }

        private async Task OnModalSavePassword(string password)
        {
            var result = await NoteService.SetPassword(url, password);
            NotePassword = password;

        }

        private async Task OnProtecMeModalSave()
        {
            var result = await NoteService.SetPassword(url, null, true);
            if (!result)
            {
                 NotificationServiceWrapper.ShowError("Error setting password!");
            }
        }

        private async Task OnModalSavePutPassword(string password)
        {
            var note = await NoteService.GetNoteByUrl(url, password);

            if (note != null)
            {
                if (note.IsSecure && note.Content == null)
                {
                    IsEditorDisabled = true;
                    NotificationServiceWrapper.ShowError("Incorrect password!");
                    IsOpenPutPassword = true;
                }
                else
                {
                    IsEditorDisabled = false;
                    IsOpenPutPassword = false;
                    NotePassword = password;
                    htmlValue = note.Content;
                }
            }
        }


        private async Task OnExecute(HtmlEditorExecuteEventArgs args)
        {
            if (args.CommandName == "ChangeUrl")
            {
                IsOpen = true;
                IsOpenPassword = false;
                IsOpenPutPassword = false;
            }
            else if (args.CommandName == "SetPassword")
            {
                IsOpen = false;
                IsOpenPassword = true;
                IsOpenPutPassword = false;
            }
            else if(args.CommandName == "GeneratePdf")
            {
                await GeneratePdf();
            }
        }


        private async Task GeneratePdf()
        {
            try
            {
                var pdfData = await NoteService.DownloadPdf(url);
                if (pdfData == null)
                {
                    NotificationServiceWrapper.ShowError("Error generating PDF!");
                    return;
                }
                var base64 = Convert.ToBase64String(pdfData);

                // Call JS to trigger download
                await JSRuntime.InvokeVoidAsync("downloadFileFromBase64", $"{url}.pdf", base64);
            }
            catch (Exception ex)
            {
                NotificationServiceWrapper.ShowError("Error generating PDF!");
            }
        }

        CancellationTokenSource cancellationToken;

        protected override async Task OnInitializedAsync()
        {
            if (string.IsNullOrEmpty(url))
            {
                url = Guid.NewGuid().ToString("N");
                Nav.NavigateTo($"/{url}", true);

            }
            else
            {
                var note = await NoteService.GetNoteByUrl(url);

                if (note != null)
                {
                    if (note.IsSecure && note.Content == null)
                    {
                        IsEditorDisabled = true;
                        IsOpenPutPassword = true;
                    }
                    else
                    {
                        htmlValue = note.Content;
                    }
                }
            }

            base.OnInitializedAsync();

        }

        async Task OnInput(string html)
        {
            cancellationToken?.Cancel();

            cancellationToken?.Dispose();

            cancellationToken = new CancellationTokenSource();

            try
            {
                var token = cancellationToken.Token;
                await Task.Delay(5000, token);

                if (!token.IsCancellationRequested)
                {
                    var result = await NoteService.CreateOrEditNoteAsync(url, html, NotePassword);
                    if (!result)
                    {
                        NotificationServiceWrapper.ShowError("Error saving note!");
                        return;
                    }
                    NotificationServiceWrapper.ShowSuccess("Note saved successfully!");
                }
            }
            catch (Exception e)
            {
                // Ignore
            }
        }


        private async Task OpenSummarizePanel()
        {
            showPanel = true;          // Open the panel frame
            noteSummary = null;        // Set to null to trigger spinner
            IsLoading = true;          // Set loading state

            try
            {
                // Await the service call
                var message = await NoteService.SummarizeNoteAsync(url);

                // Once complete, set the summary text
                noteSummary = message ?? "Failed to generate summary.";
            }
            catch (Exception ex)
            {
                noteSummary = $"An error occurred: {ex.Message}";
            }
            finally
            {
                IsLoading = false; // Stop loading spinner
            }
        }
    }
}
